# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
name: $(date:yy.M.d) $(rev:rr)

trigger:
- master

pool:
  vmImage: ubuntu-latest

#variables:
#  buildConfiguration: 'Release'

variables:
  buildConfiguration: 'Release'
  name: environments
  value: "A,B"


steps:
- script: dotnet build --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'


