# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
name: $(date:yy.M.d) $(rev:rr)

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  name: environments
  value: "A,B"

stages:
  - stage: A
    displayName: "build A .net configuration"   
    jobs:
      - deployment: A
        environment: Env-A
        strategy:
         runOnce:
          deploy:
           steps:
           - bash: stage-a test
             displayName: 'stage A build A $(buildConfiguration)'
  - stage: B
    displayName: "build B .net confuguration"
    jobs:
      - deployment: B
        environment: Env-B
        strategy:
         runOnce:
          deploy:
           steps:
           - script: dotnet build --configuration $(buildConfiguration)
             displayName: 'dotnet build B $(buildConfiguration)'





