# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core
name: $(date:yy.M.d) $(rev:rr)

trigger:
- master

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  name: environments
  value: "A,B"

stages:
  - stage: A
    displayName: "build A .net configuration"   
    jobs:
      - deployment: A
        environment: Env-A
        strategy:
         runOnce:
          deploy:
           steps:
           - task: AzureCLI@2
             inputs:
               azureSubscription: 'Visual Studio Enterprise-abonnement – MPN(15155078-e60c-450f-b805-f13f58264590)'
               scriptType: 'pscore'
               scriptLocation: 'inlineScript'
               inlineScript: 'az vm start -g ipaas-t-we-rg -n integration-vm-01'
           - script: echo hello A - start VM
             displayName: 'stage A build A $(buildConfiguration)'
  - stage: B
    displayName: "build B .net confuguration"
    jobs:
      - deployment: B
        environment: Env-B
        strategy:
         runOnce:
          deploy:
           steps:
           - task: AzureCLI@2
             inputs:
               azureSubscription: 'Visual Studio Enterprise-abonnement – MPN(15155078-e60c-450f-b805-f13f58264590)'
               scriptType: 'pscore'
               scriptLocation: 'inlineScript'
               inlineScript: 'az vm stop -g ipaas-t-we-rg -n integration-vm-01'
           - script: echo hello B - stop VM
             displayName: 'dotnet build B $(buildConfiguration)'




